<a href="https://colab.research.google.com/github/ebasantos/BackPropagation-Python/blob/master/prova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#ENTRADA
X = np.array(([2, 1], [6, 1], [4, 5]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)


X = X/np.amax(X, axis=0) 
y = y/100 

class Neural_Network(object):
  def __init__(self):
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3

    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize)

  def forward(self, X):
    self.z = np.dot(X, self.W1) 
    self.z2 = self.sigmoid(self.z) 
    self.z3 = np.dot(self.z2, self.W2) 
    o = self.sigmoid(self.z3) 
    return o 

  def sigmoid(self, s):
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    return s * (1 - s)

  def backward(self, X, y, o):
    self.o_error = y - o 
    self.o_delta = self.o_error*self.sigmoidPrime(o) 
    self.z2_error = self.o_delta.dot(self.W2.T) 
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) 

    self.W1 += X.T.dot(self.z2_delta) 
    self.W2 += self.z2.T.dot(self.o_delta)

  def train (self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)

NN = Neural_Network()

#PROXIMOS 4 DIAS
for i in xrange(4): 
  print ("Entrada: \n" + str(X)) 
  print ("Saida predita: \n" + str(NN.forward(X)))
  print ("\n")
  NN.train(X, y)

Entrada: 
[[0.33333333 0.2       ]
 [1.         0.2       ]
 [0.66666667 1.        ]]
Saida predita: 
[[0.75656879]
 [0.73085029]
 [0.67935522]]


Entrada: 
[[0.33333333 0.2       ]
 [1.         0.2       ]
 [0.66666667 1.        ]]
Saida predita: 
[[0.76591562]
 [0.74124598]
 [0.69040735]]


Entrada: 
[[0.33333333 0.2       ]
 [1.         0.2       ]
 [0.66666667 1.        ]]
Saida predita: 
[[0.7744205 ]
 [0.75084136]
 [0.70072066]]


Entrada: 
[[0.33333333 0.2       ]
 [1.         0.2       ]
 [0.66666667 1.        ]]
Saida predita: 
[[0.78217205]
 [0.75969803]
 [0.71034104]]


